name: I really don’t like something
description: ---
labels: [change request]
body:
  - type: markdown
    attributes:
      value:
        Hi! Thanks for taking the time to file this issue and make this software
        better for everyone!
  - type: textarea
    attributes:
      label: What I don't like
    validations:
      required: true
  - type: textarea
    attributes:
      label: How it could be fixed
