name: Suggest an improvement or new feature
description: ———
labels: [enhancement, under discussion]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for filing this feature request!

        Help us understanding this feature and the need for it better by filling in this form.
  - type: textarea
    attributes:
      label: Description
      description: Describe the feature in detail!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why
      description:
        Why should we add this feature? What are potential use cases for it?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot
      description:
        You can provide screenshots/mockups to better visualize your idea. Files
        can be dropped in this field
